version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          # TODO switch to package-lock.json
          key: node_modules-{{ checksum "package.json" }}
      - restore_cache:
          key: bower_components-hack1-{{ checksum "bower.json" }}
      - run:
          name: Install dependencies
          # NB. this also does bower install as postinstall step
          command: npm install
      - run:
          name: Rebuild problematic node modules
          command: npm rebuild
      - save_cache:
          # TODO switch to package-lock.json
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules/
      - save_cache:
          key: bower_components-{{ checksum "bower.json" }}
          paths:
            - bower_components/
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist/
      - deploy:
          name: Deploy
          command: |
            if [ "$PREVIEW" == "true" ]
            then
              npm run deploy -- --confirm --preview
            else
              npm run deploy -- --confirm
            fi
      - run:
          name: Check accessibility of deployed site
          command: |
            if [ "$PREVIEW" == "true" ]
            then
              npm run check-accessibility:preview
            else
              npm run check-accessibility
            fi
      - run:
          name: General QA checks
          command: npm run qa || echo "Automatic QA checks failed. Continuing anyway"
